// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// This file was generated by Prisma
// prisma.config.ts
// import { defineConfig } from "prisma/config";

// export default defineConfig({
//   schema: "prisma/schema.prisma",
//   db: {
//     url: process.env.DATABASE_URL,
//   },
// });